<a href="https://colab.research.google.com/github/Preethi3101/car_evaluation/blob/main/car_evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
% matplotlib inline
import math

dataset = pd.read_csv("car_evaluation.csv")
dataset.head(5)



vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [3]:
dataset.shape



(1727, 7)

In [4]:
col_names = ['buying', 'maintainance', 'doors', 'persons', 'lug_boot', 'safety', 'class']

dataset.columns = col_names
dataset.head(5)



buying maintainance doors persons lug_boot safety  class
0  vhigh        vhigh     2       2    small    med  unacc
1  vhigh        vhigh     2       2    small   high  unacc
2  vhigh        vhigh     2       2      med    low  unacc
3  vhigh        vhigh     2       2      med    med  unacc
4  vhigh        vhigh     2       2      med   high  unacc

In [5]:
dataset.isnull().sum()



buying          0
maintainance    0
doors           0
persons         0
lug_boot        0
safety          0
class           0
dtype: int64

In [6]:
dataset.columns

dataset['buying'],_ = pd.factorize(dataset['buying'])
dataset['maintainance'],_ = pd.factorize(dataset['maintainance'])
dataset['doors'],_ = pd.factorize(dataset['doors'])
dataset['persons'],_ = pd.factorize(dataset['persons'])
dataset['lug_boot'],_ = pd.factorize(dataset['lug_boot'])
dataset['safety'],_ = pd.factorize(dataset['safety'])
dataset.head()




buying  maintainance  doors  persons  lug_boot  safety  class
0       0             0      0        0         0       0  unacc
1       0             0      0        0         0       1  unacc
2       0             0      0        0         1       2  unacc
3       0             0      0        0         1       0  unacc
4       0             0      0        0         1       1  unacc

In [7]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,random_state=42)

X_train.shape, X_test.shape



[[0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 2]
 ...
 [3 3 3 2 2 2]
 [3 3 3 2 2 0]
 [3 3 3 2 2 1]]
['unacc' 'unacc' 'unacc' ... 'unacc' 'good' 'vgood']


((1157, 6), (570, 6))

In [8]:
from sklearn.tree import DecisionTreeClassifier
clf_en = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)


# fit the model
clf_en.fit(X_train, y_train)
y_pred = clf_en.predict(X_test)



In [9]:

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8052631578947368